//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsOnPosition
    {
        public int ID { get; set; }
        public int PositionInDishID { get; set; }
        public int IngredientID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual PositionsInDish PositionsInDish { get; set; }
    }
}
